<?php

/**
 * @file
 * Contains my_random_module.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function my_random_module_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the my_random_module module.
    case 'help.page.my_random_module':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This is a random generated custom module') . '</p>';
      return $output;

    default:
  }
}
