<?php

/**
 * @file
 * Contains creating_nodes.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function creating_nodes_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the creating_nodes module.
    case 'help.page.creating_nodes':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Helper module for creating basic nodes programmatically') . '</p>';
      return $output;

    default:
  }
}
